BOOTMAGIC_ENABLE = no           # Enable Bootmagic Lite
MOUSEKEY_ENABLE = no            # Mouse keys
EXTRAKEY_ENABLE = no            # Audio control and System control
CONSOLE_ENABLE = no             # Console for debug
COMMAND_ENABLE = no             # Commands for debug and configuration
NKRO_ENABLE = yes               # Enable NKRO
BACKLIGHT_ENABLE = yes          # Enable keyboard backlight functionality
AUDIO_ENABLE = no               # Audio output
RGBLIGHT_ENABLE = yes           # Enable WS2812 RGB underlight. 
PROGRAMMABLE_BUTTON_ENABLE = no # Enable programmable buttons
RAW_ENABLE = yes                # Enable Raw HID
LTO_ENABLE = yes                #